# Generated by Django 3.0.5 on 2020-05-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ombi_requests', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=False)),
                ('ombicred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ombi_requests.OmbiCredential')),
            ],
        ),
    ]
