# Generated by Django 3.0.5 on 2020-05-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_requestmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodule',
            name='movEnabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestmodule',
            name='musEnabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestmodule',
            name='tvEnabled',
            field=models.BooleanField(default=False),
        ),
    ]
