# Generated by Django 3.0.5 on 2020-08-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_modulename'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailCredentialType', models.CharField(choices=[('Server', 'SERVER')], default='Server', max_length=10)),
                ('USE_TLS', models.BooleanField(default=True)),
                ('HOST', models.CharField(max_length=100)),
                ('PORT', models.CharField(max_length=15)),
                ('USERNAME', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=50)),
            ],
        ),
    ]
