# Generated by Django 3.0.7 on 2020-08-10 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_logoandtitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogoandTitle',
        ),
    ]
