# Generated by Django 3.0.7 on 2020-08-10 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ombi_requests', '0002_auto_20200506_1408'),
        ('plextools_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sonarr_cal', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=False)),
                ('sonarrcred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sonarr_cal.SonarrCredential')),
            ],
        ),
        migrations.CreateModel(
            name='EmailCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailCredentialType', models.CharField(choices=[('Server', 'SERVER')], default='Server', max_length=10)),
                ('USE_TLS', models.BooleanField(default=True)),
                ('HOST', models.CharField(max_length=100)),
                ('PORT', models.CharField(max_length=15)),
                ('USERNAME', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModuleType', models.CharField(choices=[('Calendar', 'CALENDAR'), ('Request', 'REQUEST')], default='Calendar', max_length=10)),
                ('ModuleName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=False)),
                ('tvEnabled', models.BooleanField(default=False)),
                ('movEnabled', models.BooleanField(default=False)),
                ('musEnabled', models.BooleanField(default=False)),
                ('ombicred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ombi_requests.OmbiCredential')),
            ],
        ),
        migrations.CreateModel(
            name='PRequestModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=False)),
                ('tvEnabled', models.BooleanField(default=False)),
                ('movEnabled', models.BooleanField(default=False)),
                ('musEnabled', models.BooleanField(default=False)),
                ('lidarrcred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plextools_requests.LidarrCredential')),
                ('radarrcred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plextools_requests.RadarrCredential')),
                ('sonarrcred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plextools_requests.SonarrCredential')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, choices=[('discord', 'Discord'), ('email', 'Email')], max_length=15, null=True)),
                ('notificationid', models.CharField(max_length=25)),
                ('blacklist', models.TextField(blank=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CalendarModule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
