# Generated by Django 3.0.7 on 2020-08-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_logoandtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logoandtitle',
            name='logo',
        ),
    ]
