# Generated by Django 3.0.7 on 2020-08-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_logoandtitle_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogoandTitle',
            new_name='SiteSettings',
        ),
    ]
