# Generated by Django 3.0.7 on 2020-08-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200810_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='redirect',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
