# Generated by Django 3.0.7 on 2020-08-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sitesettings_redirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='redirect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CalendarModule'),
        ),
    ]
