# Generated by Django 3.0.7 on 2020-08-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200813_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='redirect',
            new_name='redirectC',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='redirectR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.RequestModule'),
        ),
    ]
