# Generated by Django 3.0.5 on 2020-05-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombi_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ombicredential',
            name='mov',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ombicredential',
            name='mus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ombicredential',
            name='tv',
            field=models.BooleanField(default=False),
        ),
    ]
