# Generated by Django 3.0.7 on 2020-08-10 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonarr_cal', '0003_auto_20200810_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SonarrNotification',
        ),
    ]
